name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          auto-activate-base: false

      - name: Create Conda Env from file
        shell: bash -l {0}
        run: |
          conda env create -f conda.yaml
          conda activate iris_env

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          conda activate iris_env
          mlflow run .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
